#!/usr/bin/env python3

##
## EPITECH PROJECT, 2020
## 205IQ
## File description:
## 205IQ
##

import sys
from math import sqrt, pi, exp

class IQ:
    def __init__(self, args : list):
        self.mu = float(sys.argv[1])
        self.sigma = float(sys.argv[2])
        if (len(args) >= 1 and len(args) <= 2):
            self.iqFirst = int(args[0])
        if (len(args) == 2):
            self.iqSecond = int(args[1])
            if (self.iqFirst > self.iqSecond):
                exit(84)

    def formula(self, x):
        try:
            f = (1 / (self.sigma * sqrt(2 * pi))) * exp((-pow(x - self.mu, 2)) / (2 * pow(self.sigma, 2)))
            return f
        except:
            return 0

    def option1(self):
        for i in range (0, 201):
            print("{} {:.5f}".format(i, self.formula(i)))

    def integral(self, begin, end):
        result = 0
        while (begin < end):
            try:
                result += exp((-pow(begin - self.mu, 2)) / (2 * pow(self.sigma, 2)))
            except:
                pass
            begin += 0.001
        try:
            final_result = (1 / (self.sigma * sqrt(2 * pi))) * result / 10
        except:
            final_result = 0
        return final_result
    
    def option2(self):
        print("{:.1f}% of people have an IQ inferior to {}".format(self.integral(0, self.iqFirst), self.iqFirst))

    def option3(self):
        print("{:.1f}% of people have an IQ between {} and {}".format(self.integral(self.iqFirst, self.iqSecond), self.iqFirst, self.iqSecond))

def checkValidNumbers():
    for i in range(1, lengthArgs):
        try:
            number = float(sys.argv[i])
            if (number < 0 or number > 200):
                exit(84)
        except:
            exit(84)

def help():
    file = open("README.md", "r")
    print(file.read())

if __name__ == "__main__":
    lengthArgs = len(sys.argv)
    if (lengthArgs == 2 and sys.argv[1] == "-h"):
        help()
        exit(0)
    if (lengthArgs < 3 or lengthArgs > 5):
        exit(84)
    checkValidNumbers()
    iq = IQ(sys.argv[3:])
    if (len(sys.argv[3:]) == 0):
        iq.option1()
    elif (len(sys.argv[3:]) == 1):
        iq.option2()
    else:
        iq.option3()
    exit(0)